org: pgchrisle
# app: aws-node-http-api
service: aws-node-http-api

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-prune-plugin
  - serverless-webpack

custom:
  webpack:
    sourcemaps: true
    webpackConfig: ./webpack.config.js
    packager: 'npm'
    includeModules: false
  serverless-offline:
    httpPort: 8080
  prune:
    automatic: true
    includeLayers: true
    number: 10

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
  
functions:
  ${file(src/modules/polls/polls.serverless.yml)}